---
server:
  host: 0.0.0.0
  port: $env["SERVER_PORT"]
database:
  url: $env["DATABASE_URL"]
kafka:
  bootstrap_servers: $env["KAFKA_BOOTSTRAP_SERVERS"]
redis:
  host: $env["REDIS_HOST"]
auth:
  issuer: $env["AUTH_ISSUER"]
  bootstrap:
    admin_email: $env["AUTH_ADMIN_EMAIL"]
    admin_password: $env["AUTH_ADMIN_PASSWORD"]

