---
server:
  host: 0.0.0.0
  port: 8080
database:
  username: $env["DATABASE_USERNAME"]
  password: $env["DATABASE_PASSWORD"]
  url: $env["DATABASE_URL"]
  port: $env["DATABASE_PORT"]
  database: $env["DATABASE_NAME"]
redis:
  host: $env["REDIS_URL"]
  port: $env["REDIS_PORT"]
auth:
  issuer: http://localhost:8080
  token_ttl_minutes: 30
  refresh_token_ttl_days: 29
  keys:
    secret: $env["AUTH_KEYS_SECRET"]
    public: $env["AUTH_KEYS_PUBLIC"]
  bootstrap:
    admin_email: admin@example.com
    admin_password: ChangeMe123!
